apiVersion: v1
kind: Service
metadata:
  name: debug-kube-sample
spec:
  selector:
    app: debug-kube-sample
  ports:
  - port: 80
    targetPort: 5255
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: debug-kube-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-kube-sample
  template:
    metadata:
      labels:
        app: debug-kube-sample
    spec:
      containers:
      - name: debug-kube-sample
        image: traefik/whoami
        ports:
        - containerPort: 5255
        env:
        - name: WHOAMI_PORT_NUMBER
          value: "5255"